# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4224c8c080357a09f7ddcbe70f120af9551cd0537f5a3f00d78a59bb565796843d7b043bd16012389ec2417595846049e50ee3445642b49ae4ce9fdddfb08441

test:
  secret_key_base: 3f16fa34e4e6610bf9b44b29fcf7c425cbc374763930710a20798902c1704c377f0f9596df995ff48e39587faeefe85c9e2c675f3a84c9170ac096eb89bf7c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
